### PR TITLE
Mini update

### PR DESCRIPTION
**Pull request by brucemiller**
Updated, shortened and clarified Semantic mini-language.

### CODE REVIEW

**Comment by davidcarlisle** [comment]
could also consider moving this to https://github.com/w3c/mathml-docs ?

**Review by NSoiffer — CHANGES_REQUESTED** [review]
I see that the examples (in the examples section) still have some names that are maybe leftover from earlier times in that they don't seem geared towards what someone would say:
* intent="unary-minus"
* intent="derivative-implicit-variable($op,$n)"
* intent="index(derivative-implicit-variable($op),$index)"
And also several more with "index", something @dginev felt was not appropriate.

Are those there because you think they are right or because you ran out of steam? If the later, you should have a prominent note warning people that the names are potentially inappropriate.

**Comment by brucemiller** [comment]
Indeed, I ran out of steam; and also couldn't figure out how to view that section nicely rendered from my fork.  I've added some clarifications and improved the literals that I used.

I do remember the discussion about "index" not being the best term, but I forget what the outcome was. I changed index to "component" for the time being.

**Comment by dginev** [comment]
>  And also several more with "index", something @dginev felt was not appropriate.

My objection was limited to the example where "index" was used for a "coordinate", which was the more precise annotation. And my main reason for objecting was that the expected speech for "coordinate" wouldn't be derivable from the "index" annotation. 

I don't think that objection carries over to indexing into actual ordered data structures, such as vectors, matrices, tuples, linked lists,... where "index" is indeed standard terminology. I think the examples in the PR are indexing into vectors, if I'm reading them right?

The descriptive stance on annotating structures that have multiple (mathematically equivalent) ways of being spoken is that any of the variants ought to be acceptable as annotation values. Ideally we have a machine-readable technique to keep "alias" information (e.g. a column in a spreadsheet), so that tools can be aware the narrations "the i-component of x" and "x at index i" would both be acceptable for the same construct `x_i`, annotated differently as `component($1,$2)` vs `index($1,$2)`.

**Comment by NSoiffer** [comment]
Since it is intentional, I'll merge the changes.

FYI: you should be able to see the page. Go to settings (top row), then choose "Pages" (on left). Then select the option to publish the page. It will then be visible at brucemiller.github.io/...  It seems like maybe you've done something funky though. I get what appears to be a redirect to http://www1.gihub.io/....

**Pull request merged**
